import React from 'react';
import { useNavigate } from 'react-router-dom';
import {
  FileText,
  CheckCircle2,
  Sparkles,
  School,
  Phone,
  ArrowRight,
  Search,
  HelpCircle,
  CreditCard,
} from 'lucide-react';

const steps = [
  { step: '01', title: 'Submit Online Application', desc: 'Complete the online application form with basic student details.' },
  { step: '02', title: 'Under Review', desc: 'Registrar reviews applicant details & verifies requirements.' },
  { step: '03', title: 'Document Verification', desc: 'Submit missing credentials (PSA, Form 138, Good Moral).' },
  { step: '04', title: 'Approval for Assessment', desc: 'Registrar approves application for tuition billing.' },
  { step: '05', title: 'Accounting Assessment', desc: 'Tuition and fee breakdown generated by Accounting.' },
  { step: '06', title: 'Payment & Sectioning', desc: 'Payment confirmation & assignment to homeroom section.' },
  { step: '07', title: 'Officially Enrolled', desc: 'Receive student credentials and official enrollment status.' },
];

const requirements = [
  'PSA Authenticated Birth Certificate (Original & 2 Photocopies)',
  'Official Report Card (Form 138 / SF9) with Learner Reference Number (LRN)',
  'Transcript of Records (Form 137 / SF10)',
  'Certificate of Good Moral Character from previous school head',
  'Recent 2×2 ID Photos (White Background, 4 Copies)',
  'JHS Certificate of Completion (Senior High School applicants)',
  'ESC / QVR Voucher Certificate (if applicable)',
];

const faqItems = [
  {
    q: 'When does official enrollment start for AY 2026–2027?',
    a: 'Enrollment registration is active both online via this portal and at Noah\'s Academy Taguig campus desk.',
  },
  {
    q: 'Are returning students required to fill out an admission form?',
    a: 'No. Returning students do NOT submit another admission application. Re-enrollment is managed directly in the Student Portal.',
  },
  {
    q: 'Can I apply if my Form 138 is pending from my previous school?',
    a: 'Yes, conditional application is accepted with a signed undertaking while awaiting Form 138 release.',
  },
];

export const AdmissionsPage: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="bg-[#FAF8FF] min-h-screen text-slate-900 py-12 lg:py-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
        {/* HERO BANNER */}
        <div className="relative rounded-3xl bg-gradient-to-br from-purple-950 via-purple-900 to-indigo-950 text-white p-8 lg:p-14 shadow-2xl overflow-hidden">
          <div className="relative z-10 max-w-3xl space-y-6">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-purple-500/20 rounded-full border border-purple-400/30 text-xs font-bold text-amber-300">
              <Sparkles className="w-4 h-4 text-amber-300" />
              <span>AY 2026–2027 Online Admission Portal</span>
            </div>

            <h1 className="text-4xl sm:text-5xl font-black tracking-tight text-white leading-tight">
              Join the Noah's Academy Family
            </h1>

            <p className="text-sm sm:text-base text-purple-200 leading-relaxed font-medium">
              Welcome prospective learners and parents! We invite new students and transferees to apply for Academic Year 2026–2027. Experience DepEd-recognized Grade 1 to 12 basic education and Senior High School academic tracks.
            </p>

            <div className="pt-4 flex flex-col sm:flex-row items-stretch sm:items-center gap-4">
              <button
                onClick={() => navigate('/admissions/apply')}
                className="px-8 py-4 bg-amber-400 hover:bg-amber-300 text-purple-950 font-black text-xs uppercase tracking-wider rounded-2xl shadow-xl shadow-amber-400/20 transition-all hover:scale-[1.02] flex items-center justify-center gap-2"
              >
                <span>Apply for Admission</span>
                <ArrowRight className="w-4 h-4" />
              </button>

              <button
                onClick={() => navigate('/admissions/track')}
                className="px-8 py-4 bg-purple-800/80 hover:bg-purple-800 text-white font-extrabold text-xs uppercase tracking-wider rounded-2xl border border-purple-500/40 transition-all flex items-center justify-center gap-2"
              >
                <Search className="w-4 h-4 text-purple-300" />
                <span>Track My Application</span>
              </button>
            </div>
          </div>
        </div>

        {/* 7-STEP ADMISSION PROCESS PIPELINE */}
        <div className="space-y-8">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="text-[10px] font-black uppercase tracking-widest text-purple-700">Official Workflow</span>
            <h2 className="text-2xl sm:text-3xl font-black text-purple-950">Admission Pipeline Overview</h2>
            <p className="text-xs text-slate-600">Trace your application from submission to official enrollment.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {steps.map((st) => (
              <div key={st.step} className="bg-white border border-purple-100 rounded-3xl p-6 shadow-xs flex flex-col justify-between space-y-4 hover:border-purple-300 transition-all">
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-2xl font-black text-amber-400 font-mono">{st.step}</span>
                    <CheckCircle2 className="w-5 h-5 text-purple-700" />
                  </div>
                  <h3 className="font-black text-sm text-purple-950">{st.title}</h3>
                  <p className="text-[11px] text-slate-600 leading-relaxed">{st.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* GRADE LEVELS & TUITION OVERVIEW GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Grade Levels */}
          <div className="lg:col-span-6 bg-white border border-purple-100 rounded-3xl p-8 shadow-xs space-y-6">
            <h3 className="text-lg font-black text-purple-950 flex items-center gap-2">
              <School className="w-5 h-5 text-purple-700" />
              <span>Grade Levels & Tracks Offered</span>
            </h3>

            <div className="space-y-4 text-xs">
              <div className="p-4 bg-purple-50/70 rounded-2xl border border-purple-100 space-y-1">
                <div className="font-extrabold text-purple-950">Elementary (Grades 1 – 6)</div>
                <p className="text-slate-600">Core foundational curriculum aligned with DepEd K-to-12 standards.</p>
              </div>

              <div className="p-4 bg-purple-50/70 rounded-2xl border border-purple-100 space-y-1">
                <div className="font-extrabold text-purple-950">Junior High School (Grades 7 – 10)</div>
                <p className="text-slate-600">Comprehensive secondary education with specialized science and technology modules.</p>
              </div>

              <div className="p-4 bg-purple-50/70 rounded-2xl border border-purple-100 space-y-1">
                <div className="font-extrabold text-purple-950">Senior High School (Grades 11 & 12)</div>
                <p className="text-slate-600">Academic Tracks: STEM, ABM, HUMSS, GAS, and ASSH.</p>
              </div>
            </div>
          </div>

          {/* Tuition Overview */}
          <div className="lg:col-span-6 bg-white border border-purple-100 rounded-3xl p-8 shadow-xs space-y-6">
            <h3 className="text-lg font-black text-purple-950 flex items-center gap-2">
              <CreditCard className="w-5 h-5 text-purple-700" />
              <span>Tuition & Fee Structure Overview</span>
            </h3>

            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between p-3.5 bg-purple-50/50 rounded-2xl border border-purple-100">
                <span className="font-bold text-slate-700">Elementary Tuition</span>
                <span className="font-mono font-black text-purple-950">₱25,000 / Year</span>
              </div>
              <div className="flex items-center justify-between p-3.5 bg-purple-50/50 rounded-2xl border border-purple-100">
                <span className="font-bold text-slate-700">Junior High Tuition</span>
                <span className="font-mono font-black text-purple-950">₱30,000 / Year</span>
              </div>
              <div className="flex items-center justify-between p-3.5 bg-purple-50/50 rounded-2xl border border-purple-100">
                <span className="font-bold text-slate-700">Senior High Tuition</span>
                <span className="font-mono font-black text-purple-950">₱35,000 / Year</span>
              </div>
              <div className="p-3 bg-amber-50 rounded-2xl border border-amber-200 text-[11px] text-amber-900 font-medium">
                * Flexible installment plans (Quarterly & Monthly) available upon accounting assessment. ESC Vouchers accepted.
              </div>
            </div>
          </div>
        </div>

        {/* FAQS SECTION */}
        <div className="bg-white border border-purple-100 rounded-3xl p-8 shadow-xs space-y-6">
          <h3 className="text-xl font-black text-purple-950 flex items-center gap-2">
            <HelpCircle className="w-5 h-5 text-purple-700" />
            <span>Frequently Asked Admissions Questions</span>
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {faqItems.map((faq, idx) => (
              <div key={idx} className="p-4 bg-purple-50/50 rounded-2xl border border-purple-100 space-y-2">
                <h4 className="font-extrabold text-xs text-purple-950">{faq.q}</h4>
                <p className="text-[11px] text-slate-600 leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>

        {/* REQUIREMENTS & FAQS GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Requirements */}
          <div className="lg:col-span-7 bg-white border border-purple-100 rounded-3xl p-8 shadow-xs space-y-6">
            <h3 className="text-lg font-black text-purple-950 flex items-center gap-2">
              <FileText className="w-5 h-5 text-purple-700" />
              <span>Required Admission Credentials</span>
            </h3>

            <div className="space-y-3">
              {requirements.map((req, idx) => (
                <div key={idx} className="flex items-start space-x-3 p-3 bg-purple-50/70 rounded-2xl border border-purple-100">
                  <CheckCircle2 className="w-4 h-4 text-purple-700 shrink-0 mt-0.5" />
                  <span className="text-xs font-semibold text-purple-950">{req}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Registrar Contact & Assistance */}
          <div className="lg:col-span-5 bg-gradient-to-br from-purple-950 to-indigo-950 text-white rounded-3xl p-8 space-y-6 shadow-xl text-center">
            <h3 className="text-xl font-black text-amber-300">Need Assistance?</h3>
            <p className="text-xs text-purple-200 leading-relaxed font-medium">
              Our Admissions & Registrar team is available Monday through Friday, 8:00 AM to 5:00 PM.
            </p>

            <div className="p-4 bg-purple-900/60 rounded-2xl border border-purple-700/50 space-y-2 text-xs font-mono">
              <div className="flex items-center justify-center gap-2">
                <Phone className="w-4 h-4 text-amber-300" />
                <span>(02) 8888-NOAH</span>
              </div>
              <div>admissions@noahsacademy.edu.ph</div>
              <div className="text-[10px] text-purple-300 font-sans">Arca South Campus, Taguig City</div>
            </div>

            <button
              onClick={() => navigate('/admissions/apply')}
              className="w-full py-3.5 bg-amber-400 hover:bg-amber-300 text-purple-950 font-black text-xs uppercase tracking-wider rounded-2xl shadow-lg transition-all"
            >
              Start Admission Application
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
